#!/bin/bash
#
# Mirror, to or from a remote host, recursively, the specified relative directory,
# even though $HOME here and there may be different.
#
# Usage: mirror <to|from> <host> <directory>

cmd=$1
server=$2
shift 2
here=$PWD/
homeslash=$HOME/
path_on_server=${here/$homeslash/}
        
# Remove trailing slash as necessary in each path spec
paths=()
for p in $@; do
    paths+=( "${p%/}" )
done

case $cmd in
	from)
        # Process variable number of command line arguments, so we can sync multiple paths
        # with one invocation of rsync. This is so user doesn't have to keep typing in
        # the password.
        # Don't make a brace-enclosed, comma-separated list for one element
        if [ "${#paths[@]}" -gt 1 ]; then
            IFS=, eval 'pathstring="${paths[*]}"'
            pathstring="{${pathstring}}"
        else
            pathstring="$paths"
        fi
		echo rsync -avz --progress ${server}:${path_on_server}${pathstring} .
	    rsync -avz --progress ${server}:${path_on_server}${pathstring} .
	;;
	to)
        pathstring="${paths[@]}"
		echo rsync -avz --progress ${pathstring} ${server}:${path_on_server}
		rsync -avz --progress ${pathstring} ${server}:${path_on_server}
	;;
esac
